# Generated by Django 5.2 on 2025-09-02 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listings",
            options={"ordering": ["-created_at"]},
        ),
    ]
