# Generated by Django 5.2 on 2025-09-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_alter_listings_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listings",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
