# Generated by Django 5.2 on 2025-06-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_usersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="display_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
