# Generated by Django 5.2 on 2025-09-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_usersettings_bio_usersettings_display_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="has_onboarded",
            field=models.BooleanField(default=False),
        ),
    ]
