# Generated by Django 5.2 on 2025-09-01 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_customuser_has_onboarded"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_seller",
        ),
    ]
